# Generated by Django 2.1.2 on 2019-07-06 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=False, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
